# Postgres settings
# #################
# development:
#   adapter: postgresql
#   host: localhost
#   database: kandan_development
#   pool: 5
#   timeout: 5000

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
